name: ezflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.19.0
  - pandas>=1.2.0
  - scikit-learn>=0.24.0
  - pytorch>=1.8.0
  - tensorflow>=2.4.0
  - rdkit>=2022.3.1
  - mlflow>=1.20.0
  - tensorboard>=2.4.0
  - optuna>=2.8.0
  - pytest>=6.0.0
  - black>=21.5b2
  - isort>=5.8.0
  - flake8>=3.9.0
  - dash>=2.0.0
  - plotly>=5.0.0
  - jupyter
  - ipykernel
  - pip:
    - -e . 